# Generated by Django 2.1.2 on 2018-11-05 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=30)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pending_transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default="6TQ=J'@l'=Dn9En{4xV", max_length=12, unique=True)),
                ('transaction_id', models.CharField(default='6sz8nwZNWTAZp', max_length=14, unique=True)),
                ('u_id', models.IntegerField()),
                ('pending_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last1', models.FloatField(default=0)),
                ('transaction_id_1', models.CharField(max_length=12, unique=True)),
                ('date1', models.DateField(auto_now=True, verbose_name='%Y-%m-%d')),
                ('last2', models.FloatField(default=0)),
                ('transaction_id_2', models.CharField(max_length=12, unique=True)),
                ('date2', models.DateField(auto_now=True, verbose_name='%Y-%m-%d')),
                ('last3', models.FloatField(default=0)),
                ('transaction_id_3', models.CharField(max_length=12, unique=True)),
                ('date3', models.DateField(auto_now=True, verbose_name='%Y-%m-%d')),
                ('last4', models.FloatField(default=0)),
                ('transaction_id_4', models.CharField(max_length=12, unique=True)),
                ('date4', models.DateField(auto_now=True, verbose_name='%Y-%m-%d')),
                ('last5', models.FloatField(default=0)),
                ('transaction_id_5', models.CharField(max_length=12, unique=True)),
                ('date5', models.DateField(auto_now=True, verbose_name='%Y-%m-%d')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credits.AccountBalance')),
            ],
        ),
    ]
