# Generated by Django 2.1.2 on 2018-11-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_auto_20181105_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='key',
            field=models.CharField(default='44wzRDL01$lo:"ST4m', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='lBGVGmMATBszTf', max_length=14, unique=True),
        ),
    ]
