# Generated by Django 2.1.2 on 2018-11-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_auto_20181105_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='key',
            field=models.CharField(default="Ajr$L;+Q%^ra_r2$0'Z", max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='6Mx18pHLP2mwbo58', max_length=14, unique=True),
        ),
    ]
