# Generated by Django 2.1.2 on 2018-11-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0006_auto_20181105_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='EkxJKn9JpwuVM', max_length=14, unique=True),
        ),
    ]
