# Generated by Django 2.1.2 on 2018-11-06 19:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0009_auto_20181105_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='key',
            field=models.CharField(default=uuid.UUID('06bc9310-a8bb-4eac-9a4e-090e26ca8a69'), max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='sF4B2Lh9X5Xdm', max_length=14, unique=True),
        ),
    ]
