# Generated by Django 2.1.2 on 2018-11-06 19:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0010_auto_20181107_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='key',
            field=models.CharField(default=uuid.UUID('94be1689-8d44-4cd3-a37b-aa380307544b'), max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='lZQWEtlHTppmY', max_length=14, unique=True),
        ),
    ]
