# Generated by Django 2.1.2 on 2018-11-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0011_auto_20181107_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='key',
            field=models.CharField(default='2c7b1d35', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='roOMAPgs5cri', max_length=14, unique=True),
        ),
    ]
