# Generated by Django 2.1.2 on 2018-11-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0013_auto_20181107_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='key',
            field=models.CharField(default='ffe514c0ce', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='A6C264DC6C', max_length=14, unique=True),
        ),
    ]
