# Generated by Django 2.1.2 on 2018-11-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0014_auto_20181107_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='key',
            field=models.CharField(default=models.CharField(default='6ac63c80dc', unique=True), max_length=12),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='F894C7FB1E', max_length=14, unique=True),
        ),
    ]
