# Generated by Django 2.1.2 on 2018-11-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0015_auto_20181107_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='key',
            field=models.CharField(default='3ed28367c5', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='90B3A14A6E', max_length=14, unique=True),
        ),
    ]
