# Generated by Django 2.1.2 on 2018-11-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0016_auto_20181107_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='key',
            field=models.CharField(default='e1da38b280', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='579538E5D7', max_length=14, unique=True),
        ),
    ]
