# Generated by Django 2.1.2 on 2018-11-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0017_auto_20181107_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='key',
            field=models.CharField(default='7739fd1bea', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='CF4415F342', max_length=14, unique=True),
        ),
    ]
