# Generated by Django 2.1.2 on 2018-11-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0019_auto_20181109_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='key',
            field=models.CharField(default='595926', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='371D52E504', max_length=14, unique=True),
        ),
    ]
