# Generated by Django 2.1.2 on 2018-11-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0023_auto_20181110_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='key',
            field=models.CharField(default='598953', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='B230F63BD8', max_length=14, unique=True),
        ),
    ]
