# Generated by Django 2.1.2 on 2018-11-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0024_auto_20181110_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='key',
            field=models.CharField(default=0, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='A4E504AB49', max_length=14, unique=True),
        ),
    ]
