# Generated by Django 2.1.2 on 2018-11-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0025_auto_20181110_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='93CA4A90FC', max_length=14, unique=True),
        ),
    ]
