# Generated by Django 2.1.2 on 2018-11-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0028_auto_20181111_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='7D17A6A00551', max_length=14, unique=True),
        ),
    ]
