# Generated by Django 2.1.2 on 2018-11-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0029_auto_20181111_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_redeem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField(default=666781, max_length=6, unique=True)),
                ('transaction_id', models.CharField(default='38EE1776B6EF', max_length=14, unique=True)),
                ('userid', models.IntegerField()),
                ('redeem_amount', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='EB81F39F9053', max_length=14, unique=True),
        ),
    ]
