# Generated by Django 2.1.2 on 2018-11-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0030_auto_20181111_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_redeem',
            name='code',
            field=models.IntegerField(default=666781, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_redeem',
            name='transaction_id',
            field=models.CharField(default='B625B211E809', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='2806C4FD8512', max_length=14, unique=True),
        ),
    ]
