# Generated by Django 2.1.2 on 2018-11-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0031_auto_20181111_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_redeem',
            name='transaction_id',
            field=models.CharField(default='627FD15CE8AF', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='88BA308F1484', max_length=14, unique=True),
        ),
    ]
