# Generated by Django 2.1.2 on 2018-11-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0032_auto_20181111_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_redeem',
            name='transaction_id',
            field=models.CharField(default='C93F9E87CFA3', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='7228A8289235', max_length=14, unique=True),
        ),
    ]
