# Generated by Django 2.1.2 on 2018-11-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0033_auto_20181111_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_redeem',
            name='transaction_id',
            field=models.CharField(default='B14D5BD26EB8', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='D285949089E0', max_length=14, unique=True),
        ),
    ]
