# Generated by Django 2.1.2 on 2018-11-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0034_auto_20181111_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_redeem',
            name='transaction_id',
            field=models.CharField(default='8B0F3BA55BA5', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='7733C1DFE056', max_length=14, unique=True),
        ),
    ]
