# Generated by Django 2.1.2 on 2018-11-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0035_auto_20181111_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_redeem',
            name='transaction_id',
            field=models.CharField(default='55A38DBBE092', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='77DB2CCC6651', max_length=14, unique=True),
        ),
    ]
