# Generated by Django 2.1.2 on 2018-11-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0036_auto_20181111_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_redeem',
            name='transaction_id',
            field=models.CharField(default='B7A216CE5CDD', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='1D941E08E9B7', max_length=14, unique=True),
        ),
    ]
