# Generated by Django 2.1.2 on 2018-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0038_auto_20181112_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_redeem',
            name='transaction_id',
            field=models.CharField(default='7A8AB2540379', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='3CADD8C67900', max_length=14, unique=True),
        ),
    ]
